# Generated by Django 2.0.6 on 2018-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmas', '0004_auto_20180607_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default='Female', max_length=10),
        ),
    ]
